[window]
opacity = 1
padding = {x = 5, y = 5}

[env]
term = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Medium"}
size = 12.0

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors=true
 
[colors.primary]
background = '{{base00}}'
foreground = '{{base05}}'

[colors.normal]
black   = '{{base01}}'
red     = '{{base08}}'
green   = '{{base0B}}'
yellow  = '{{base0A}}'
blue    = '{{base0D}}'
magenta = '{{base0E}}'
cyan    = '{{base0C}}'
white   = '{{base07}}'
