#!/bin/bash

alpha='dd'
background='#282a36'
selection='#44475a'
comment='#6272a4'

# gruvbox
yellow='{{base0A}}'
orange='{{base09}}'
red='{{base08}}'
magenta='{{base0E}}'
blue='{{base0D}}'
cyan='{{base0C}}'
green='{{base0B}}'


i3lock \
  --insidever-color=$selection$alpha \
  --insidewrong-color=$selection$alpha \
  --inside-color=$selection$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$orange$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$orange$alpha \
  --ring-color=$green $alpha \
  --line-uses-ring \
  --keyhl-color=$yellow$alpha \
  --bshl-color=$orange$alpha \
  --separator-color=$selection$alpha \
  --verif-color=$cyan \
  --wrong-color=$orange\
  --modif-color=$orange\
  --layout-color=$green \
  --date-color=$green \
  --time-color=$green \
  --clock \
  --indicator \
  --time-str="%H:%M:%S" \
  --date-str="%A %e %B %Y" \
  --verif-text="verifying..." \
  --wrong-text="wrong!" \
  --noinput="no input" \
  --lock-text="locking..." \
  --lockfailed="lock failed!" \
  --radius=240 \
  --ring-width=30 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
  --time-font="FiraCode Nerd Font" \
  --date-font="FiraCode Nerd Font" \
  --layout-font="FiraCode Nerd Font" \
  --verif-font="FiraCode Nerd Font" \
  --wrong-font="FiraCode Nerd Font" \
  -i ~/.config/i3/{{theme_name}}.png \
