default_keybindings = true
use_nerdfont = true
notify = true

[theme]
background = "{{base00}}"
primary = "{{base05}}"
secondary = "{{base06}}"
title = "{{base0B}}"
playing = "{{base0C}}"
playing_bg = "{{base02}}"
playing_selected = "{{base06}}"
highlight = "{{base07}}"
highlight_bg = "{{base02}}"
error = "{{base05}}"
error_bg = "{{base08}}"
statusbar_progress = "{{base0D}}"
statusbar_bg = "{{base00}}"
statusbar = "{{base0B}}"
cmdline = "{{base05}}"
cmdline_bg = "{{base02}}"
search_match = "{{base0A}}"
