default_keybindings = true
use_nerdfont = true
notify = true

[theme]
background = "#192330"
primary = "#cdcecf"
secondary = "#aeafb0"
title = "#81b29a"
playing = "#63cdcf"
playing_bg = "#29394f"
playing_selected = "#aeafb0"
highlight = "#e4e4e5"
highlight_bg = "#29394f"
error = "#cdcecf"
error_bg = "#c94f6d"
statusbar_progress = "#719cd6"
statusbar_bg = "#192330"
statusbar = "#81b29a"
cmdline = "#cdcecf"
cmdline_bg = "#29394f"
search_match = "#dbc074"
