[window]
opacity = 0.8
padding = {x = 5, y = 5}

[env]
term = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style="SemiBold"}
size = 14.0

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors=true
