[window]
opacity = 0.95
padding = {x = 10, y = 40}
decorations = "Transparent"
startup_mode = "Maximized"

[env]
term = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Medium"}
size = 18.0

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors=true
 
# Gruvbox colors
[colors.primary]
background = '#202020'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# Nightfox colors
# [colors.primary]
# background = "#131a24"
# foreground = "#cdcecf"
# dim_foreground = "#aeafb0"
# bright_foreground = "#d6d6d7"
# 
# # [colors.cursor]
# # text = "#cdcecf"
# # cursor = "#aeafb0"
# # 
# # [colors.vi_mode_cursor]
# # text = "#cdcecf"
# # cursor = "#63cdcf"
# 
# [colors.search.matches]
# foreground = "#cdcecf"
# background = "#3c5372"
# 
# [colors.search.focused_match]
# foreground = "#cdcecf"
# background = "#81b29a"
# 
# [colors.footer_bar]
# foreground = "#cdcecf"
# background = "#29394f"
# 
# [colors.hints.start]
# foreground = "#cdcecf"
# background = "#f4a261"
# 
# [colors.hints.end]
# foreground = "#cdcecf"
# background = "#29394f"
# 
# [colors.selection]
# text = "#cdcecf"
# background = "#2b3b51"
# 
# [colors.normal]
# black = "#393b44"
# red = "#c94f6d"
# green = "#81b29a"
# yellow = "#dbc074"
# blue = "#719cd6"
# magenta = "#9d79d6"
# cyan = "#63cdcf"
# white = "#dfdfe0"
# 
# [colors.bright]
# black = "#575860"
# red = "#d16983"
# green = "#8ebaa4"
# yellow = "#e0c989"
# blue = "#86abdc"
# magenta = "#baa1e2"
# cyan = "#7ad5d6"
# white = "#e4e4e5"
# 
# [colors.dim]
# black = "#30323a"
# red = "#ab435d"
# green = "#6e9783"
# yellow = "#baa363"
# blue = "#6085b6"
# magenta = "#8567b6"
# cyan = "#54aeb0"
# white = "#bebebe"
# 
# [[colors.indexed_colors]]
# index = 16
# color = "#f4a261"
# 
# [[colors.indexed_colors]]
# index = 17
# color = "#d67ad2"
