[[themes]]
name = "Gruvbox"
[themes.palette]
background = "#282828"
foreground = "#fbf1c7"
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
orange = "#d65d0e"
white = "#bdae93"
bright_black = "#665c54"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_orange = "#fe8019"
bright_white = "#ebdbb2"
